# Generated by Django 4.1.2 on 2024-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='consecutive_spam_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='spam_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='spam_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
