# Generated by Django 4.1.2 on 2024-06-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_profile_blocked_users_profile_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contacts',
        ),
    ]
